import os
import shutil
import hashlib
import time
import argparse
import sys
from pathlib import Path

# This file is mostly generated by Gemini.
#
# This executable is designed to resolve selective sync conflicts in Dropbox 
# by comparing the normal folder with its corresponding "Selective Sync Conflict" (SSC) folder.
# Originally discussed in https://github.com/kinu-garage/essay_in_idleness/issues/460
#
# Note: The very feature in this file may NOT be available via existing tools e.g. rsync
# (ref. https://github.com/kinu-garage/essay_in_idleness/issues/460#issuecomment-4063024485)
# in that this tool allows to look at a custom naming format (e.g. " (Selective Sync Conflict)")
# to identify the folders to care.

def get_md5(file_path):
    hash_md5 = hashlib.md5()
    try:
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(4096), b""):
                hash_md5.update(chunk)
        return hash_md5.hexdigest()
    except Exception:
        return None

def sync_conflict_folders(base_path, dry_run=False):
    start_time = time.time()
    path = Path(base_path).resolve()
    
    # Validation: Ensure the path actually exists
    if not path.exists():
        print(f"Error: The path '{path}' does not exist.")
        sys.exit(1)

    ssc_suffix = " (Selective Sync Conflict)"
    
    stats = {
        "folders_created": [], "folders_skipped": 0,
        "files_updated": [], "files_skipped": 0
    }
    
    log_name = "ssc_resolution_dryrun.txt" if dry_run else "ssc_resolution_log.txt"
    log_path = path / log_name
    
    try:
        with open(log_path, "w", encoding="utf-8") as log_file:
            def log_print(msg):
                print(msg)
                log_file.write(msg + "\n")

            log_print(f"{'[DRY RUN] ' if dry_run else ''}Target Root: {path}")
            log_print("-" * 60)

            for ssc_dir in path.rglob(f"*{ssc_suffix}"):
                if not ssc_dir.is_dir(): continue
                
                normal_dir = Path(str(ssc_dir).replace(ssc_suffix, ""))
                if not normal_dir.exists() or not normal_dir.is_dir(): continue

                log_print(f"\n[PAIR] Folder Comparison:\n  Normal: {normal_dir}\n  SSC:    {ssc_dir}")

                for root, dirs, files in os.walk(normal_dir):
                    rel_path = Path(root).relative_to(normal_dir)
                    target_root = ssc_dir / rel_path

                    # 1. Directory Comparison
                    for d in dirs:
                        ssc_subdir = target_root / d
                        log_print(f"  [DIR PAIR] Checking: {rel_path / d}")
                        if not ssc_subdir.exists():
                            log_print(f"    -> Missing in SSC. {'(Simulating)' if dry_run else 'Copying'} tree...")
                            if not dry_run:
                                shutil.copytree(Path(root) / d, ssc_subdir, dirs_exist_ok=True)
                            stats["folders_created"].append(str(ssc_subdir))
                        else:
                            stats["folders_skipped"] += 1

                    # 2. File Comparison
                    for f in files:
                        normal_file = Path(root) / f
                        ssc_file = target_root / f
                        log_print(f"  [FILE PAIR] Checking: {rel_path / f}")

                        should_act = False
                        if not ssc_file.exists():
                            log_print(f"    -> Missing in SSC. {'(Simulating)' if dry_run else 'Copying'}...")
                            should_act = True
                        else:
                            n_md5, s_md5 = get_md5(normal_file), get_md5(ssc_file)
                            if n_md5 != s_md5:
                                if normal_file.stat().st_mtime > ssc_file.stat().st_mtime:
                                    log_print(f"    -> Newer version in Normal. {'(Simulating)' if dry_run else 'Updating'}...")
                                    should_act = True
                                else:
                                    log_print("    -> Different MD5, but Normal is not newer. Skipping.")
                                    stats["files_skipped"] += 1
                            else:
                                log_print("    -> Identical. Skipping.")
                                stats["files_skipped"] += 1

                        if should_act:
                            if not dry_run:
                                target_root.mkdir(parents=True, exist_ok=True)
                                shutil.copy2(normal_file, ssc_file)
                            stats["files_updated"].append(str(ssc_file))

            # Final Summary
            duration = time.time() - start_time
            summary_header = "\n" + "="*60 + f"\n{'DRY RUN ' if dry_run else ''}FINAL EXECUTION SUMMARY\n" + "="*60
            log_print(summary_header)
            log_print(f"Top Level Directory: {path}")
            log_print(f"Log File Location:   {log_path}")
            log_print(f"Execution Time:      {duration:.2f} seconds")
            
            log_print(f"\nFolders {'(to be) Created' if dry_run else 'Created'} ({len(stats['folders_created'])}):")
            for folder in stats["folders_created"]: log_print(f"  [+] {folder}")
            log_print(f"Folders Skipped: {stats['folders_skipped']}")

            log_print(f"\nFiles {'(to be) Updated' if dry_run else 'Updated'} ({len(stats['files_updated'])}):")
            for f_path in stats["files_updated"]: log_print(f"  [+] {f_path}")
            log_print(f"Files Skipped: {stats['files_skipped']}")
            log_print("="*60)
            
    except PermissionError:
        print(f"Fatal Error: Permission denied when writing log to {log_path}")
        sys.exit(1)

if __name__ == "__main__":
    # Use a custom ArgumentParser to handle unrecognized arguments strictly
    parser = argparse.ArgumentParser(
        description="Resolve Selective Sync Conflicts by syncing data from Normal folders to '... (Selective Sync Conflict)' folders.",
        epilog="Example: python3 resolve_ssc.py /path/to/sync/dir --dry-run"
    )
    
    # Set the path to be a required positional argument to prevent "hanging" behavior
    parser.add_argument("path", help="The absolute or relative path to scan for conflict folders.")
    parser.add_argument("--dry-run", action="store_true", help="Simulate actions and output to ssc_resolution_dryrun.txt without writing files.")

    # parse_args() automatically handles unknown arguments by printing an error and exiting
    args = parser.parse_args()

    sync_conflict_folders(args.path, dry_run=args.dry_run)