#!/usr/bin/env python

import argparse

from util.Util import replace_str_in_file

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Replace a line of string in all the files found at the folder tree in the given path.')
    parser.add_argument('match_str_regex', default='<version>.*</version>', help='File pattern to match. You can use regular expression.')
    parser.add_argument('new_str', default='', help='String to be used.')
    parser.add_argument('target_path', default='.', help='Path under which target file(s) will be searched at. Full or relative path (relative path is not tested).')
    parser.add_argument('target_filename', default='package.xml', help='Name of the file(s) to be manipulated.')
    args = parser.parse_args()

    replace_str_in_file(args.target_filename, args.target_path, args.match_str_regex, args.new_str)
